services:
  web:
    image: ktbloomq:sellswords
    build: .
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/:ro
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql:Z